### ISSUE TITLE
Hello friend

### ISSUE THREAD

**Issue by fjj355** [pawelorzech/dokkan-battle-bot#5]
Hello friend
I want to buy your robot

**Comment by fjj355** [comment]
![image](https://user-images.githubusercontent.com/55411622/64995079-e79a6100-d90c-11e9-9654-8223fec1c199.png)

**Comment by fjj355** [comment]
Lack of a working robot
Do you need to buy it for you, friend

**Comment by pawelorzech** [comment]
No. There's tutorial in the readme how to use it with python.
