### ISSUE TITLE
Is there requirements.txt file ?

### ISSUE THREAD

**Issue by smirkkk** [pawelorzech/dokkan-battle-bot#8]
Thank you. 
And my OS is Windows 10 64bit. Does it matter?

**Comment by pawelorzech** [comment]
There's no requirements. 

pip3 install six
pip3 install pyinstaller
pip3 install colorama
pip3 install orator
pip3 install pycrypto - https://github.com/dlitz/pycrypto
pip3 install PySimpleGUI
pip3 install requests
